/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coconut.ui.admin;
import coconut.db.DBConnection;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author navee
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
private String currentUsername;
    private int currentUserId;

    public AdminDashboard(String username, int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUsername = username;
        this.currentUserId = userId;
        loadDashboard();
    }

private void loadDashboard() {
        try {
            Connection conn = DBConnection.getConnection();

            // Total farmers
            PreparedStatement ps1 = conn.prepareStatement("SELECT COUNT(*) FROM user WHERE role = 'farmer'");
            ResultSet rs1 = ps1.executeQuery();
            if (rs1.next()) lblTotalFarmers.setText(String.valueOf(rs1.getInt(1)));

            // Total plots
            PreparedStatement ps2 = conn.prepareStatement("SELECT COUNT(*) FROM plot");
            ResultSet rs2 = ps2.executeQuery();
            if (rs2.next()) lblTotalPlots.setText(String.valueOf(rs2.getInt(1)));

            // Active season
            PreparedStatement ps3 = conn.prepareStatement("SELECT * FROM season WHERE status = 'active' LIMIT 1");
            ResultSet rs3 = ps3.executeQuery();
            if (rs3.next()) {
                lblActiveSeason.setText(rs3.getString("season_name"));

                // Total harvest for active season
                PreparedStatement ps4 = conn.prepareStatement("SELECT SUM(nut_count) FROM harvest WHERE season_id = ?");
                ps4.setInt(1, rs3.getInt("season_id"));
                ResultSet rs4 = ps4.executeQuery();
                if (rs4.next()) lblTotalHarvest.setText(String.valueOf(rs4.getInt(1)));
            } else {
                lblActiveSeason.setText("None");
                lblTotalHarvest.setText("0");
            }

            // Recent inspections table
            PreparedStatement ps5 = conn.prepareStatement(
                "SELECT i.inspection_date, p.plot_name, u.full_name, i.health_status " +
                "FROM inspection i " +
                "JOIN plot p ON i.plot_id = p.plot_id " +
                "JOIN user u ON i.officer_id = u.user_id " +
                "ORDER BY i.inspection_date DESC LIMIT 10"
            );
            ResultSet rs5 = ps5.executeQuery();
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Date", "Plot", "Officer", "Health Status"}, 0
            );
            while (rs5.next()) {
                model.addRow(new Object[]{
                    rs5.getDate("inspection_date"),
                    rs5.getString("plot_name"),
                    rs5.getString("full_name"),
                    rs5.getString("health_status")
                });
            }
            tblInspections.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading dashboard: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcomeAdmin = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTotalPlots = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblActiveSeason = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTotalFarmers = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTotalHarvest = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInspections = new javax.swing.JTable();
        btnSeasons = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcomeAdmin.setText("Welcome Admin");
        jPanel1.add(lblWelcomeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalPlots.setText("0");
        jPanel2.add(lblTotalPlots, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel6.setText("Total Plots");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 48, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 70));

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblActiveSeason.setText("-");
        jPanel3.add(lblActiveSeason, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 26, -1, -1));

        jLabel7.setText("Active Season");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 70));

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalFarmers.setText("0");
        jPanel4.add(lblTotalFarmers, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setText("Total Farmers");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 46, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 70));

        jPanel5.setBackground(new java.awt.Color(153, 255, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalHarvest.setText("0");
        jPanel5.add(lblTotalHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 26, -1, -1));

        jLabel1.setText("Total Harvest");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 170, 90));

        tblInspections.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblInspections);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        btnSeasons.setText("Manage Seasons");
        btnSeasons.addActionListener(this::btnSeasonsActionPerformed);
        jPanel1.add(btnSeasons, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        btnUsers.setText("Manage Users");
        btnUsers.addActionListener(this::btnUsersActionPerformed);
        jPanel1.add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, -1));

        btnReports.setText("Reports");
        btnReports.addActionListener(this::btnReportsActionPerformed);
        jPanel1.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        jLabel2.setText("Recent Inspections");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSeasonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeasonsActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_btnSeasonsActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_btnReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard("admin", 1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSeasons;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblActiveSeason;
    private javax.swing.JLabel lblTotalFarmers;
    private javax.swing.JLabel lblTotalHarvest;
    private javax.swing.JLabel lblTotalPlots;
    private javax.swing.JLabel lblWelcomeAdmin;
    private javax.swing.JTable tblInspections;
    // End of variables declaration//GEN-END:variables
}
