/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coconut.ui.officer;
import coconut.db.DBConnection;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author navee
 */
public class InspectionForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InspectionForm.class.getName());

    /**
     * Creates new form InspectionForm
     */
   private String currentUsername;
    private int currentUserId;
    private int currentSeasonId = -1;
    private int selectedInspectionId = -1;

    public InspectionForm(String username, int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUsername = username;
        this.currentUserId = userId;
        loadPlots();
        loadActiveSeason();
        loadInspections();
        setSize(900, 600);
setLocationRelativeTo(null);
setResizable(false); // this prevents resizing - optional
// Set main background color
jPanel1.setBackground(new java.awt.Color(245, 245, 245));
    }

    private void loadPlots() {
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT p.plot_id, p.plot_name, u.full_name FROM plot p JOIN user u ON p.farmer_id = u.user_id"
            );
            ResultSet rs = ps.executeQuery();
            cmbPlot.removeAllItems();
            while (rs.next()) {
                cmbPlot.addItem(rs.getInt("plot_id") + " - " + rs.getString("plot_name") + " (" + rs.getString("full_name") + ")");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading plots: " + e.getMessage());
        }
    }

    private void loadActiveSeason() {
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement("SELECT season_id FROM season WHERE status = 'Active' LIMIT 1");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                currentSeasonId = rs.getInt("season_id");
            } else {
                JOptionPane.showMessageDialog(this, "No active season found!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading season: " + e.getMessage());
        }
    }

    private void loadInspections() {
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT i.inspection_id, i.inspection_date, p.plot_name, i.health_status, i.pest_issues, i.recommendation " +
                "FROM inspection i " +
                "JOIN plot p ON i.plot_id = p.plot_id " +
                "WHERE i.officer_id = ? " +
                "ORDER BY i.inspection_date DESC"
            );
            ps.setInt(1, currentUserId);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Date", "Plot", "Health Status", "Pest Issues", "Recommendation"}, 0
            );
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("inspection_id"),
                    rs.getDate("inspection_date"),
                    rs.getString("plot_name"),
                    rs.getString("health_status"),
                    rs.getString("pest_issues"),
                    rs.getString("recommendation")
                });
            }
            tblInspections.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading inspections: " + e.getMessage());
        }
    }

    private void clearForm() {
        cmbPlot.setSelectedIndex(0);
        dateInspection.setDate(null);
        cmbHealthStatus.setSelectedIndex(0);
        txtPestIssues.setText("");
        txtRecommendation.setText("");
        selectedInspectionId = -1;
    }

    private int getSelectedPlotId() {
        String selected = cmbPlot.getSelectedItem().toString();
        return Integer.parseInt(selected.split(" - ")[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        cmbPlot = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateInspection = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cmbHealthStatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPestIssues = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRecommendation = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInspections = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Inspection Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        cmbPlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel2.setText("Select Plot");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel3.setText("Inspection Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        jPanel1.add(dateInspection, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jLabel4.setText("Health Status");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        cmbHealthStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good", "At_Risk", "Critical" }));
        jPanel1.add(cmbHealthStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel5.setText("Pest Issues");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        jPanel1.add(txtPestIssues, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 70, -1));

        jLabel6.setText("Recommendation");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        txtRecommendation.setColumns(20);
        txtRecommendation.setRows(5);
        jScrollPane1.setViewportView(txtRecommendation);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        tblInspections.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblInspections.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInspectionsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblInspections);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jLabel7.setText("Past Insepections");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblInspectionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInspectionsMouseClicked
        int row = tblInspections.getSelectedRow();
        if (row != -1) {
            selectedInspectionId = (int) tblInspections.getValueAt(row, 0);
            dateInspection.setDate((java.util.Date) tblInspections.getValueAt(row, 1));
            cmbHealthStatus.setSelectedItem(tblInspections.getValueAt(row, 3).toString());
            txtPestIssues.setText(tblInspections.getValueAt(row, 4).toString());
            txtRecommendation.setText(tblInspections.getValueAt(row, 5).toString());
        }
    }//GEN-LAST:event_tblInspectionsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (cmbPlot.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this, "No plots available!");
            return;
        }
        if (dateInspection.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select inspection date!");
            return;
        }
        if (currentSeasonId == -1) {
            JOptionPane.showMessageDialog(this, "No active season found!");
            return;
        }
        try {
            Connection conn = DBConnection.getConnection();
            String sql = "INSERT INTO inspection (plot_id, season_id, officer_id, inspection_date, health_status, pest_issues, recommendation) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, getSelectedPlotId());
            ps.setInt(2, currentSeasonId);
            ps.setInt(3, currentUserId);
            ps.setDate(4, new java.sql.Date(dateInspection.getDate().getTime()));
            ps.setString(5, cmbHealthStatus.getSelectedItem().toString());
            ps.setString(6, txtPestIssues.getText());
            ps.setString(7, txtRecommendation.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Inspection added successfully!");
            loadInspections();
            clearForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error adding inspection: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedInspectionId == -1) {
            JOptionPane.showMessageDialog(this, "Please select an inspection to update!");
            return;
        }
        try {
            Connection conn = DBConnection.getConnection();
            String sql = "UPDATE inspection SET health_status=?, pest_issues=?, recommendation=? WHERE inspection_id=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, cmbHealthStatus.getSelectedItem().toString());
            ps.setString(2, txtPestIssues.getText());
            ps.setString(3, txtRecommendation.getText());
            ps.setInt(4, selectedInspectionId);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Inspection updated successfully!");
            loadInspections();
            clearForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating inspection: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new coconut.ui.officer.OfficerDashboard(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InspectionForm("officer", 3).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbHealthStatus;
    private javax.swing.JComboBox<String> cmbPlot;
    private com.toedter.calendar.JDateChooser dateInspection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblInspections;
    private javax.swing.JTextField txtPestIssues;
    private javax.swing.JTextArea txtRecommendation;
    // End of variables declaration//GEN-END:variables
}
