/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coconut.ui.officer;
import coconut.db.DBConnection;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author navee
 */
public class OfficerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OfficerDashboard.class.getName());

    /**
     * Creates new form OfficerDashboard
     */
private String currentUsername;
    private int currentUserId;

    public OfficerDashboard(String username, int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUsername = username;
        this.currentUserId = userId;
        loadDashboard();
        setSize(900, 600);
setLocationRelativeTo(null);
setResizable(false); // this prevents resizing - optional
// Set main background color
jPanel1.setBackground(new java.awt.Color(245, 245, 245));
    }

    private void loadDashboard() {
        lblWelcome.setText("Welcome, " + currentUsername);
        try {
            Connection conn = DBConnection.getConnection();

            // Load recent inspections done by this officer
            PreparedStatement ps = conn.prepareStatement(
                "SELECT i.inspection_date, p.plot_name, i.health_status, i.recommendation " +
                "FROM inspection i " +
                "JOIN plot p ON i.plot_id = p.plot_id " +
                "WHERE i.officer_id = ? " +
                "ORDER BY i.inspection_date DESC LIMIT 10"
            );
            ps.setInt(1, currentUserId);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Date", "Plot", "Health Status", "Recommendation"}, 0
            );
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getDate("inspection_date"),
                    rs.getString("plot_name"),
                    rs.getString("health_status"),
                    rs.getString("recommendation")
                });
            }
            tblInspections.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading dashboard: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInspections = new javax.swing.JTable();
        btnInspection = new javax.swing.JButton();
        btnActivities = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setText("welcome");
        jPanel1.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        tblInspections.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInspections);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        btnInspection.setText("Add Inspection");
        btnInspection.addActionListener(this::btnInspectionActionPerformed);
        jPanel1.add(btnInspection, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btnActivities.setText("View Activities");
        btnActivities.addActionListener(this::btnActivitiesActionPerformed);
        jPanel1.add(btnActivities, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel1.setText("Recent Inspections");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new coconut.ui.LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInspectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInspectionActionPerformed
        new coconut.ui.officer.InspectionForm(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInspectionActionPerformed

    private void btnActivitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivitiesActionPerformed
        new coconut.ui.officer.ViewActivities(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActivitiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OfficerDashboard("officer", 3).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivities;
    private javax.swing.JButton btnInspection;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblInspections;
    // End of variables declaration//GEN-END:variables
}
