/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coconut.ui.farmer;
import coconut.db.DBConnection;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author navee
 */
public class ActivityForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ActivityForm.class.getName());

    /**
     * Creates new form ActivityForm
     */
    private String currentUsername;
    private int currentUserId;
    private int currentPlotId = -1;
    private int currentSeasonId = -1;
    private int selectedActivityId = -1;

    public ActivityForm(String username, int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUsername = username;
        this.currentUserId = userId;
        loadPlotAndSeason();
        loadActivities();
        setSize(900, 600);
setLocationRelativeTo(null);
setResizable(false); // this prevents resizing - optional
// Set main background color
jPanel1.setBackground(new java.awt.Color(245, 245, 245));
    }

    private void loadPlotAndSeason() {
        try {
            Connection conn = DBConnection.getConnection();

            // Get farmer's plot
            PreparedStatement ps = conn.prepareStatement("SELECT plot_id FROM plot WHERE farmer_id = ?");
            ps.setInt(1, currentUserId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                currentPlotId = rs.getInt("plot_id");
            } else {
                JOptionPane.showMessageDialog(this, "You have not registered a plot yet!");
            }

            // Get active season
            PreparedStatement ps2 = conn.prepareStatement("SELECT season_id FROM season WHERE status = 'Active' LIMIT 1");
            ResultSet rs2 = ps2.executeQuery();
            if (rs2.next()) {
                currentSeasonId = rs2.getInt("season_id");
            } else {
                JOptionPane.showMessageDialog(this, "No active season found!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }

    private void loadActivities() {
        if (currentPlotId == -1) return;
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT * FROM activity WHERE plot_id = ? ORDER BY activity_date DESC"
            );
            ps.setInt(1, currentPlotId);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Activity Type", "Date", "Notes"}, 0
            );
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("activity_id"),
                    rs.getString("activity_type"),
                    rs.getDate("activity_date"),
                    rs.getString("notes")
                });
            }
            tblActivities.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading activities: " + e.getMessage());
        }
    }

    private void clearForm() {
        cmbActivityType.setSelectedIndex(0);
        dateActivity.setDate(null);
        txtNotes.setText("");
        selectedActivityId = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActivities = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbActivityType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        dateActivity = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Farm Activities");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        tblActivities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblActivitiesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblActivities);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabel2.setText("Activity Type");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        cmbActivityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fertilizing", "Irrigation", "Pest_control", "Pruning", "Other" }));
        jPanel1.add(cmbActivityType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel3.setText("Activity Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        jPanel1.add(dateActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel4.setText("Notes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblActivitiesMouseClicked
        int row = tblActivities.getSelectedRow();
        if (row != -1) {
            selectedActivityId = (int) tblActivities.getValueAt(row, 0);
            cmbActivityType.setSelectedItem(tblActivities.getValueAt(row, 1).toString());
            dateActivity.setDate((java.util.Date) tblActivities.getValueAt(row, 2));
            txtNotes.setText(tblActivities.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_tblActivitiesMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (currentPlotId == -1 || currentSeasonId == -1) {
            JOptionPane.showMessageDialog(this, "Plot or active season not found!");
            return;
        }
        if (dateActivity.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a date!");
            return;
        }
        try {
            Connection conn = DBConnection.getConnection();
            String sql = "INSERT INTO activity (plot_id, season_id, recorded_by, activity_type, activity_date, notes) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, currentPlotId);
            ps.setInt(2, currentSeasonId);
            ps.setInt(3, currentUserId);
            ps.setString(4, cmbActivityType.getSelectedItem().toString());
            ps.setDate(5, new java.sql.Date(dateActivity.getDate().getTime()));
            ps.setString(6, txtNotes.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Activity added successfully!");
            loadActivities();
            clearForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error adding activity: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedActivityId == -1) {
            JOptionPane.showMessageDialog(this, "Please select an activity to delete!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this activity?");
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection conn = DBConnection.getConnection();
                String sql = "DELETE FROM activity WHERE activity_id = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, selectedActivityId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Activity deleted successfully!");
                loadActivities();
                clearForm();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error deleting activity: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new coconut.ui.farmer.FarmerDashboard(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ActivityForm("farmer", 2).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cmbActivityType;
    private com.toedter.calendar.JDateChooser dateActivity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblActivities;
    private javax.swing.JTextArea txtNotes;
    // End of variables declaration//GEN-END:variables
}
