/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coconut.ui.farmer;
import coconut.db.DBConnection;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author navee
 */
public class FarmerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FarmerDashboard.class.getName());

    /**
     * Creates new form FarmerDashboard
     */
   private String currentUsername;
    private int currentUserId;
    private int currentPlotId = -1;

    public FarmerDashboard(String username, int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUsername = username;
        this.currentUserId = userId;
        loadDashboard();
        setSize(900, 600);
setLocationRelativeTo(null);
setResizable(false); // this prevents resizing - optional
// Set main background color
jPanel1.setBackground(new java.awt.Color(245, 245, 245));
    }

    private void loadDashboard() {
        lblWelcome.setText("Welcome, " + currentUsername);
        try {
            Connection conn = DBConnection.getConnection();

            // Load plot summary
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM plot WHERE farmer_id = ?");
            ps.setInt(1, currentUserId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                currentPlotId = rs.getInt("plot_id");
                lblPlotName.setText(rs.getString("plot_name"));
                lblLocation.setText(rs.getString("location"));
                lblTreeCount.setText(String.valueOf(rs.getInt("tree_count")));
            } else {
                lblPlotName.setText("Not registered");
                lblLocation.setText("-");
                lblTreeCount.setText("-");
            }

            // Load recent activities
            if (currentPlotId != -1) {
                PreparedStatement ps2 = conn.prepareStatement(
                    "SELECT activity_type, activity_date, notes FROM activity WHERE plot_id = ? ORDER BY activity_date DESC LIMIT 5"
                );
                ps2.setInt(1, currentPlotId);
                ResultSet rs2 = ps2.executeQuery();
                DefaultTableModel model = new DefaultTableModel(
                    new String[]{"Activity Type", "Date", "Notes"}, 0
                );
                while (rs2.next()) {
                    model.addRow(new Object[]{
                        rs2.getString("activity_type"),
                        rs2.getDate("activity_date"),
                        rs2.getString("notes")
                    });
                }
                tblActivities.setModel(model);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading dashboard: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPlotName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTreeCount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActivities = new javax.swing.JTable();
        btnPlot = new javax.swing.JButton();
        btnActivity = new javax.swing.JButton();
        btnInspections = new javax.swing.JButton();
        btnHarvest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setText("Welcome,Farmer");
        jPanel1.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("My Plot");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel2.setText("Plot Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblPlotName.setText("jLabel3");
        jPanel2.add(lblPlotName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel4.setText("Location:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblLocation.setText("jLabel5");
        jPanel2.add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel6.setText("Tree Count:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblTreeCount.setText("jLabel7");
        jPanel2.add(lblTreeCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 190));

        jLabel3.setText("Recent Activities");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        tblActivities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblActivities);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        btnPlot.setText("My Plot");
        btnPlot.addActionListener(this::btnPlotActionPerformed);
        jPanel1.add(btnPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        btnActivity.setText("Log Activity");
        btnActivity.addActionListener(this::btnActivityActionPerformed);
        jPanel1.add(btnActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, -1));

        btnInspections.setText("View Inspections");
        btnInspections.addActionListener(this::btnInspectionsActionPerformed);
        jPanel1.add(btnInspections, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, -1));

        btnHarvest.setText("Record Harvest");
        btnHarvest.addActionListener(this::btnHarvestActionPerformed);
        jPanel1.add(btnHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new coconut.ui.LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlotActionPerformed
       new coconut.ui.farmer.PlotForm(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlotActionPerformed

    private void btnActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivityActionPerformed
        new coconut.ui.farmer.ActivityForm(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActivityActionPerformed

    private void btnHarvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarvestActionPerformed
      new coconut.ui.farmer.HarvestForm(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHarvestActionPerformed

    private void btnInspectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInspectionsActionPerformed
       new coconut.ui.farmer.ViewInspections(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInspectionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FarmerDashboard("farmer", 2).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivity;
    private javax.swing.JButton btnHarvest;
    private javax.swing.JButton btnInspections;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPlot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPlotName;
    private javax.swing.JLabel lblTreeCount;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblActivities;
    // End of variables declaration//GEN-END:variables
}
