/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coconut.ui.farmer;
import coconut.db.DBConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author navee
 */
public class HarvestForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HarvestForm.class.getName());

    /**
     * Creates new form HarvestForm
     */
    private String currentUsername;
    private int currentUserId;
    private int currentPlotId = -1;
    private int currentSeasonId = -1;
    private int selectedHarvestId = -1;

    public HarvestForm(String username, int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUsername = username;
        this.currentUserId = userId;
        loadPlotAndSeason();
        loadHarvests();
        setSize(900, 600);
setLocationRelativeTo(null);
setResizable(false); // this prevents resizing - optional
// Set main background color
jPanel1.setBackground(new java.awt.Color(245, 245, 245));
    }

    private void loadPlotAndSeason() {
        try {
            Connection conn = DBConnection.getConnection();

            // Get farmer's plot
            PreparedStatement ps = conn.prepareStatement("SELECT plot_id FROM plot WHERE farmer_id = ?");
            ps.setInt(1, currentUserId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                currentPlotId = rs.getInt("plot_id");
            } else {
                JOptionPane.showMessageDialog(this, "You have not registered a plot yet!");
            }

            // Get active season
            PreparedStatement ps2 = conn.prepareStatement("SELECT season_id FROM season WHERE status = 'Active' LIMIT 1");
            ResultSet rs2 = ps2.executeQuery();
            if (rs2.next()) {
                currentSeasonId = rs2.getInt("season_id");
            } else {
                JOptionPane.showMessageDialog(this, "No active season found!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }

    private void loadHarvests() {
        if (currentPlotId == -1) return;
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT * FROM harvest WHERE plot_id = ? ORDER BY harvest_date DESC"
            );
            ps.setInt(1, currentPlotId);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Date", "Nut Count", "Price Per Nut", "Quality", "Total Value", "Notes"}, 0
            );
            while (rs.next()) {
                int nutCount = rs.getInt("nut_count");
                double price = rs.getDouble("price_per_nut");
                double total = nutCount * price;
                model.addRow(new Object[]{
                    rs.getInt("harvest_id"),
                    rs.getDate("harvest_date"),
                    nutCount,
                    price,
                    rs.getString("quality_grade"),
                    String.format("%.2f", total),
                    rs.getString("notes")
                });
            }
            tblHarvest.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading harvests: " + e.getMessage());
        }
    }

    private void clearForm() {
        dateHarvest.setDate(null);
        txtNutCount.setText("");
        txtPrice.setText("");
        cmbQuality.setSelectedIndex(0);
        txtNotes.setText("");
        lblTotalValue.setText("0.00");
        selectedHarvestId = -1;
    }

    private void calculateTotal() {
        try {
            int nutCount = Integer.parseInt(txtNutCount.getText());
            double price = Double.parseDouble(txtPrice.getText());
            double total = nutCount * price;
            lblTotalValue.setText(String.format("%.2f", total));
        } catch (NumberFormatException e) {
            lblTotalValue.setText("0.00");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHarvest = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNutCount = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        dateHarvest = new com.toedter.calendar.JDateChooser();
        cmbQuality = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Harvest Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        tblHarvest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHarvest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHarvestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHarvest);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel2.setText("Harvest Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setText("Nut Count");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setText("Price Per Nut(Rs.)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, -1));

        jLabel5.setText("Quality Grade");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));

        jLabel6.setText("Notes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtNutCount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNutCountKeyReleased(evt);
            }
        });
        jPanel1.add(txtNutCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, -1));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 90, -1));
        jPanel1.add(dateHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        cmbQuality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        jPanel1.add(cmbQuality, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel7.setText("Total Value(Rs.):");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        lblTotalValue.setText("jLabel8");
        jPanel1.add(lblTotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHarvestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHarvestMouseClicked
        int row = tblHarvest.getSelectedRow();
        if (row != -1) {
            selectedHarvestId = (int) tblHarvest.getValueAt(row, 0);
            dateHarvest.setDate((java.util.Date) tblHarvest.getValueAt(row, 1));
            txtNutCount.setText(tblHarvest.getValueAt(row, 2).toString());
            txtPrice.setText(tblHarvest.getValueAt(row, 3).toString());
            cmbQuality.setSelectedItem(tblHarvest.getValueAt(row, 4).toString());
            lblTotalValue.setText(tblHarvest.getValueAt(row, 5).toString());
            txtNotes.setText(tblHarvest.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_tblHarvestMouseClicked

    private void txtNutCountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNutCountKeyReleased
        calculateTotal();
    }//GEN-LAST:event_txtNutCountKeyReleased

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        calculateTotal();
    }//GEN-LAST:event_txtPriceKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       if (currentPlotId == -1 || currentSeasonId == -1) {
            JOptionPane.showMessageDialog(this, "Plot or active season not found!");
            return;
        }
        if (dateHarvest.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a harvest date!");
            return;
        }
        if (txtNutCount.getText().isEmpty() || txtPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter nut count and price!");
            return;
        }
        try {
            int nutCount = Integer.parseInt(txtNutCount.getText());
            double price = Double.parseDouble(txtPrice.getText());

            Connection conn = DBConnection.getConnection();
            String sql = "INSERT INTO harvest (plot_id, season_id, harvest_date, nut_count, price_per_nut, quality_grade, notes) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, currentPlotId);
            ps.setInt(2, currentSeasonId);
            ps.setDate(3, new java.sql.Date(dateHarvest.getDate().getTime()));
            ps.setInt(4, nutCount);
            ps.setDouble(5, price);
            ps.setString(6, cmbQuality.getSelectedItem().toString());
            ps.setString(7, txtNotes.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Harvest recorded successfully!");
            loadHarvests();
            clearForm();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nut count and price must be numbers!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error recording harvest: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedHarvestId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a harvest to update!");
            return;
        }
        try {
            int nutCount = Integer.parseInt(txtNutCount.getText());
            double price = Double.parseDouble(txtPrice.getText());

            Connection conn = DBConnection.getConnection();
            String sql = "UPDATE harvest SET harvest_date=?, nut_count=?, price_per_nut=?, quality_grade=?, notes=? WHERE harvest_id=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setDate(1, new java.sql.Date(dateHarvest.getDate().getTime()));
            ps.setInt(2, nutCount);
            ps.setDouble(3, price);
            ps.setString(4, cmbQuality.getSelectedItem().toString());
            ps.setString(5, txtNotes.getText());
            ps.setInt(6, selectedHarvestId);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Harvest updated successfully!");
            loadHarvests();
            clearForm();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nut count and price must be numbers!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating harvest: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedHarvestId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a harvest to delete!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this harvest?");
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection conn = DBConnection.getConnection();
                String sql = "DELETE FROM harvest WHERE harvest_id = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, selectedHarvestId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Harvest deleted successfully!");
                loadHarvests();
                clearForm();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error deleting harvest: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new coconut.ui.farmer.FarmerDashboard(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HarvestForm("farmer", 2).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbQuality;
    private com.toedter.calendar.JDateChooser dateHarvest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JTable tblHarvest;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtNutCount;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
