/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coconut.ui.farmer;
import java.sql.*;
import javax.swing.JOptionPane;
import coconut.db.DBConnection;
/**
 *
 * @author navee
 */
public class PlotForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlotForm.class.getName());

    /**
     * Creates new form PlotForm
     */
    private String currentUsername;
    private int currentUserId;
    private int currentPlotId = -1;

    public PlotForm(String username, int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUsername = username;
        this.currentUserId = userId;
        loadPlot();
        setSize(900, 600);
setLocationRelativeTo(null);
setResizable(false); // this prevents resizing - optional
// Set main background color
jPanel1.setBackground(new java.awt.Color(245, 245, 245));
    }

    private void loadPlot() {
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM plot WHERE farmer_id = ?");
            ps.setInt(1, currentUserId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                currentPlotId = rs.getInt("plot_id");
                txtPlotName.setText(rs.getString("plot_name"));
                txtLocation.setText(rs.getString("location"));
                txtTreeCount.setText(String.valueOf(rs.getInt("tree_count")));
                txtLandSize.setText(String.valueOf(rs.getDouble("land_size_acres")));
                btnSave.setText("Update");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading plot: " + e.getMessage());
        }
    }

    private void clearForm() {
        txtPlotName.setText("");
        txtLocation.setText("");
        txtTreeCount.setText("");
        txtLandSize.setText("");
        currentPlotId = -1;
        btnSave.setText("Save");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPlotName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtTreeCount = new javax.swing.JTextField();
        txtLandSize = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("My Plot");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel2.setText("Plot Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel3.setText("Location");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel4.setText("Tree Count");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel5.setText("Land Size(Acres)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        jPanel1.add(txtPlotName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 100, -1));
        jPanel1.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 100, -1));
        jPanel1.add(txtTreeCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 110, -1));
        jPanel1.add(txtLandSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 100, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new coconut.ui.farmer.FarmerDashboard(currentUsername, currentUserId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtPlotName.getText().isEmpty() || txtLocation.getText().isEmpty()
                || txtTreeCount.getText().isEmpty() || txtLandSize.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!");
            return;
        }
        
        try {
            int treeCount = Integer.parseInt(txtTreeCount.getText());
            double landSize = Double.parseDouble(txtLandSize.getText());

            Connection conn = DBConnection.getConnection();
            
            if (currentPlotId == -1) {
                // Double check no plot exists already
            PreparedStatement check = conn.prepareStatement("SELECT COUNT(*) FROM plot WHERE farmer_id = ?");
            check.setInt(1, currentUserId);
            ResultSet rs = check.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "You already have a registered plot!");
            return;
}
                // Insert new plot
                String sql = "INSERT INTO plot (farmer_id, plot_name, location, tree_count, land_size_acres) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, currentUserId);
                ps.setString(2, txtPlotName.getText());
                ps.setString(3, txtLocation.getText());
                ps.setInt(4, treeCount);
                ps.setDouble(5, landSize);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Plot registered successfully!");
            } else {
                // Update existing plot
                String sql = "UPDATE plot SET plot_name=?, location=?, tree_count=?, land_size_acres=? WHERE plot_id=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, txtPlotName.getText());
                ps.setString(2, txtLocation.getText());
                ps.setInt(3, treeCount);
                ps.setDouble(4, landSize);
                ps.setInt(5, currentPlotId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Plot updated successfully!");
            }
            loadPlot();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tree count and land size must be numbers!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saving plot: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        txtPlotName.setEditable(true);
        txtLocation.setEditable(true);
        txtTreeCount.setEditable(true);
        txtLandSize.setEditable(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> new PlotForm("farmer", 2).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLandSize;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPlotName;
    private javax.swing.JTextField txtTreeCount;
    // End of variables declaration//GEN-END:variables
}
